### ISSUE TITLE
Why SAX? Can we use StAX?

### ISSUE THREAD

**Issue by PolarNick239** [IFMO-MobDev-2013/lesson6#1]
Why we must use SAX?
StAX not taking more memory, but it is more pretty! Can we use this, more actual alternative?

**Comment by thevery** [comment]
No
21.10.2013 19:45 ÐÏÌØÚÏ×ÁÔÅÌØ "Nickolay Polyarniy" notifications@github.com
ÎÁÐÉÓÁÌ:

**Comment by PolarNick239** [comment]
Ok, thanks for the fast response.
But StAX still is the best choice :)
