### ISSUE TITLE
XML parser selection

### ISSUE THREAD

**Issue by gfv** [IFMO-MobDev-2013/lesson6#24]
It is quite unusual for a feed to exceed 100kb (i.e. Lenta.ru and bash.im's feeds are ~80kb combined) and extremely unlikely to be larger than 1Mb. I'm pulling numbers out of thin air, but the point is -- effective memory usage is not really an issue here.

Is it absolutely necessary to choose clunky state-machiney SAX interface to parse XML over clean, simple and object-oriented DOM augmented with XPath?

**Comment by thevery** [comment]
lenta.ru is 213 kb:
wget http://lenta.ru/rss
Length: 218476 (213K) [application/rss+xml]

**Comment by thevery** [comment]
dom+xpath=memory and GC hog
