### ISSUE TITLE
Android's SAX - is it allowed?

### ISSUE THREAD

**Issue by Martoon-00** [IFMO-MobDev-2013/lesson6#28]
I happen to write SAX parser using android.sax. So I have two questions:
1) Is it permitted to do that?
2) Function RootElement applies some restrictions on the name of xml's root tag, is it possible to pass through it? (for lesson7)
As I remember, this realization is said to be easier and faster, so it's reasoned to be used

**Comment by thevery** [comment]
1) Using built-in classed is preferred in most cases, so yes.
2) Unfortunately, I don't understand your question :( But there is no changes required in parser for task 7.

**Comment by Martoon-00** [comment]
I meant that RootElement function require one argument - name of prospective root tag, but it differs from one feed to another. There is any way to take this into account?

**Comment by thevery** [comment]
Just use plain old DefaultHandler
29.10.2013 16:38 ÐÏÌØÚÏ×ÁÔÅÌØ "é×ÁÎÏ× ëÏÓÔÑ" notifications@github.com
ÎÁÐÉÓÁÌ:
