### ISSUE TITLE
UI for channels list

### ISSUE THREAD

**Issue by Genyaz** [IFMO-MobDev-2013/lesson6#3]
Should the UI for channels also include the UI for RSS feed?
Is it acceptable to have for example one activity for a list of channels and another activity for RSS feed of the selected channel?

**Comment by thevery** [comment]
You must have 3 activities - channels list, articles list and content view.
21.10.2013 22:26 ÐÏÌØÚÏ×ÁÔÅÌØ "Genyaz" notifications@github.com ÎÁÐÉÓÁÌ:

**Comment by Genyaz** [comment]
OK, this part of the task is clear now.

**Comment by thevery** [comment]
updated task text
