### ISSUE TITLE
IntentService - is it mandatory?

### ISSUE THREAD

**Issue by georgeee** [IFMO-MobDev-2013/lesson6#4]
You've said, we should use IntentService. As I understood, reading documentation, it's just a solution for handling a bunch of AsynchTask's (e.g. for updating feed data). Can I just not use it, if I already have quite well-formed solution for this case, which doesn't use IntentService?

And by the way, two more questions. Is implementing background-updating strict condition? Must we use here databases, or for the stage we can just keep data in memory (which means, forgetting it after application shutdown)?

Thanks for answers!

**Comment by thevery** [comment]
what solution do you have already?

database support goes to the part #3 - the main idea for adding IS and AM
to part #2 (and mostly not using them) is to make last part as simple as
possible (because it will be the hardest part anyway).

2013/10/23 George Agapov notifications@github.com

**Comment by georgeee** [comment]
Skeleton for handling various Http request on top of AsyncTask. E.g. downloading new feed is performed like this:
new FeedReaderTask(query){
            @Override
            protected void onPostExecute(Feed feed) {
                if(feed == null) return;
                feedListAdapter.add(feed);
                feedListAdapter.notifyDataSetInvalidated();
            }
        }.executeOnHttpTaskExecutor();

But, in fact, I feel, like I begin to understand, what is the purpose of IS using.
Am I right, that it should be embedded for easy handling just any type of requests from UI. Not only loading the rss by url, but just requests like "give me entries from i-th to j-th in feed with <id>" or "give me entry_id's content"
And is designed to stop ACtivity from thinking, where from data comes and how some background actions are performed?

**Comment by ghost** [comment]
Sorry for interrupting, but what do you mean by "the hardest part"? The most difficult to implement or the most CPU, time and web traffic consuming? And am I right that the last part is #2 ?

**Comment by thevery** [comment]
AsyncTask is no-go for UI-less background updates - that's the main reason. Easier handling comes out from using database+cursor+notifications, rather that AT/IS.

**Comment by thevery** [comment]
@Seidhe "hardest" means a lot of code to understand, write and debug. I think that 3 parts will be enough for this task (and current is only second).

**Comment by ghost** [comment]
@thevery Yes, I've got it. Thanks! :)

**Comment by georgeee** [comment]
One more question.
I've understood, that we shoul update our data in background via AlarmManager. And we don't use database at the moment. Where should we put our downloaded data though?

**Comment by thevery** [comment]
as you can see in the task, no IS-activity interaction is required at the moment
